### ISSUE TITLE
Questions about hyperparameters for EACL2021 paper

### ISSUE THREAD

**Issue by ddehun** [Guzpenha/transformer_rankers#3]
Hi. I have a question about the experimental setup on your EACL2021 paper, On the Calibration and Uncertainty of Neural Learning to Rank Models.

How did the number of forward pass for MCdropout (T) and the number of model for Ensemble (M) are set?

Thank you!

**Comment by Guzpenha** [comment]
Hi, we did not do any hyperparameter tuning for those and used 5 to be able to run experiments in a reasonable time. I believe previous work uses 5 as well (https://papers.nips.cc/paper/2017/file/9ef2ed4b7fd2c810847ffa5fa85bce38-Paper.pdf).
