### ISSUE TITLE
Sampling pool for negative candidates

### ISSUE THREAD

**Issue by ddehun** [Guzpenha/transformer_rankers#7]
Hi. Thank you for sharing your work.

I have a question about the sampling pool of different negative types in 3.3.2 Cross Negative Sampling in the paper.
When you retrieve negative candidates to make a test set, where did you sample them?? (utterances in train set vs. test set).
Sorry to make a silly question, and thank you for your help in advance.

**Comment by Guzpenha** [comment]
Hi, it is not a silly question :))

You can see this code: https://github.com/Guzpenha/transformer_rankers/blob/1e0d47f5db0f1b32b4d2d044dd2a146bea8346d6/transformer_rankers/examples/crr_bert_ranker_example.py#L57

You will see that when I do the cross NS experiments 
(https://github.com/Guzpenha/transformer_rankers/blob/uncertainty_estimation/transformer_rankers/scripts/run_bert_crr_diff_neg_samplers.sh ) I call the script above. The negatives are selected from the union of train and val. This way there are more chances we find some difficult negative samples!! 

Hope it helps
